version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=synapsis_db
    ports:
      - "5432:5432"
  #   volumes:
  #     - data-volume:/var/lib/postgresql/data
  # redis:
  #   image: redis:7-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgres://postgres:postgres@postgres:5432/synapsis_db?sslmode=disable
      - PORT=8080
      - SECRET-thejwtsecret
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      # - redis
#     entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
#     command: ["/app/main"]
# volumes:
#   data-volume:
